# Generated by Django 5.2.3 on 2025-07-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
