# Generated by Django 5.2.3 on 2025-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='location',
            field=models.CharField(default='New-York, USA', max_length=100),
            preserve_default=False,
        ),
    ]
