# Generated by Django 5.2.3 on 2025-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingitem_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_items/'),
        ),
    ]
