# Generated by Django 5.2.3 on 2025-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_bookingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/booking_items/'),
        ),
    ]
